/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "btnClear": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "clearClickHandler", "rightImageWidth": 5, "text": "Clear" },
    "btnChange": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "changeClickHandler", "rightImageWidth": 5, "text": "Change" },
    "btnTranslate": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "btnTranslateHandler", "rightImageWidth": 5, "text": "Translate" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "LanguageDetectText": { "creationFunction": "CreateText", "text": "as" },
    "text": { "creationFunction": "CreateText", "text": "Source Text Language:" },
    "text1": { "creationFunction": "CreateText", "text": "Translation in Language:" },
    "text3": { "creationFunction": "CreateText", "text": "Text Tranlsator version 1.0" },
    "text4": { "creationFunction": "CreateText", "text": "LionPRO - Mykola Lys." },
    "text5": { "creationFunction": "CreateText", "text": "Text Translator powered by Google" },
    "text6": { "creationFunction": "CreateText", "text": "Feel free to contact me at job.mlys@gmail.com" },
    "text7": { "creationFunction": "CreateText", "text": "Home page - jobmlys.sites.google.com" },
    "text8": { "creationFunction": "CreateText", "text": " powered by Google translation engine" }
};
